### ISSUE TITLE
Layout view can't get $this->title from content view

### ISSUE THREAD

**Issue by wensonsmith** [Patroklo/yii2-blade#1]
Yii2 can set page title from content view use  `$this->title`.  [Document here](http://www.yiiframework.com/doc-2.0/guide-structure-views.html#setting-page-titles)

But if i render a `.blade` template, layout view can't get `$this->tile`, i don't known how to fix it.

Thanks for your extension. It's very useful.

**Comment by Patroklo** [comment]
Hi. The object `$this` can't be used in Blade templates due to compatibility problems with the Blade system callings. 

So, instead of this object I made the `$view` object that has the same functionalities than the `$this` in a normal layout system.
