### ISSUE TITLE
Adding link to laravel blade docs

### ISSUE THREAD

**Issue by DenisAlliswell** [Patroklo/yii2-blade#3]
Nice job, @Patroklo !

I guess it's good idea to put in repo docs the link to Laravel blade docs https://laravel.com/docs/5.2/blade just for completeness sake.

Thanks for the work you've done!

**Comment by Patroklo** [comment]
That's a good idea, but, to make sure about the url, shouldn't better link to the master version instead of the 5.2? I have no idea about the time that url could be working...

**Comment by DenisAlliswell** [comment]
@Patroklo you are right, that would be better.

**Comment by Patroklo** [comment]
Ok, added the documentation link, thanks!
