### ISSUE TITLE
problem with render

### ISSUE THREAD

**Issue by alikmanukian** [Patroklo/yii2-blade#4]
HI, 
I hav problem in blade file, when I try to render there another blade file. 

Maximum execution time of 30 seconds exceeded

**Comment by Patroklo** [comment]
Hi, I don't have right now a yii2 installation, let me make one an try the system. While doing that. Can you post the code you are using to include the files?

**Comment by alikmanukian** [comment]
If i use, $view->render('someview.blade'), 
Maximum execution time of 30 seconds exceeded

But if @include('someview.blade') everything is ok.

**Comment by Patroklo** [comment]
I've just seen the problem, trying to repair it. I'll let you know when it's done.

**Comment by Patroklo** [comment]
I have updated the library, check it out if it works for you.

**Comment by alikmanukian** [comment]
Good job. 
Thank you very much !
